---
##
 # Copyright OpenSearch Contributors
 # SPDX-License-Identifier: Apache-2.0
##

# Settings file for the report instances index
index:
  number_of_shards: "1" # The data size is not expected to be big so keeping it 1 shard
  auto_expand_replicas: "0-2"
