name: Test and Build Kibana Reports

on: [pull_request, push]

env:
  PLUGIN_NAME: opendistroReportsKibana
  OD_VERSION: 1.13.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v1

      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: elastic/kibana
          ref: v7.10.2
          path: kibana

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.23.1"

      - name: Move Kibana Reports to Plugins Dir
        run: mv kibana-reports ../kibana/plugins/${{ env.PLUGIN_NAME }}

      - name: Kibana Plugin Bootstrap
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: cd ../kibana/plugins/${{ env.PLUGIN_NAME }}; yarn kbn bootstrap

      - name: Test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: cd ../kibana/plugins/${{ env.PLUGIN_NAME }}; yarn test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: Kibana-reports
          directory: ../kibana/plugins/
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Artifact
        run: |
          cd ../kibana/plugins/${{ env.PLUGIN_NAME }}
          yarn build
          mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip

      - name: Upload Artifact For Linux x64
        uses: actions/upload-artifact@v1
        with:
          name: kibana-reports-linux-x64
          path: ../kibana/plugins/${{ env.PLUGIN_NAME }}/build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip

      - name: Upload Artifact For Linux arm64
        uses: actions/upload-artifact@v1
        with:
          name: kibana-reports-linux-arm64
          path: ../kibana/plugins/${{ env.PLUGIN_NAME }}/build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip

      - name: Upload Artifact For Windows
        uses: actions/upload-artifact@v1
        with:
          name: kibana-reports-windows-x64
          path: ../kibana/plugins/${{ env.PLUGIN_NAME }}/build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip
