name: integration tests workflow

on: [pull_request, push]

jobs:
  run-tests:
    name: Run integration tests with security

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11]
        node-version: [14.x]
        opensearch-version: [ latest ]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Reporting CLI
        uses: actions/checkout@v2

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Download and run Opensearch and Dashboard
        run: |
          wget https://opensearch.org/samples/docker-compose.yml
          docker-compose up --detach
      
      - name: Check Docker containers
        run: docker ps -a

      - name: Add sample data
        run: |
          curl -XPOST -u 'admin:admin' 'http://localhost:5601/api/sample_data/flights' -H 'osd-xsrf:true'
          
      - name: Run integration tests
        run: |
          cd ./reporting-cli/
          npm install
          npm test
          cd ..
      
      - name: Clean up container
        if: always()
        run: |
          docker-compose down
